# Generated by Django 6.0.3 on 2026-03-14 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomScriptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomScriptLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataDisplayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=150, null=True)),
                ('max_channel_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EEGChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Standardized channel name (e.g., 'Fp1', 'Cz')", max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrequencyBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Alpha, Beta, Theta', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('low_hz', models.FloatField()),
                ('high_hz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetaDataGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StimulusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StimulusPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_character', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameter', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.componentcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('source', models.TextField(help_text='File path or raw script code')),
                ('parameter', models.JSONField(blank=True, default=dict, help_text='Default JSON parameters for the script')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.customscriptcategory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.customscriptlanguage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.datadisplaycategory')),
            ],
        ),
        migrations.CreateModel(
            name='DataDisplayCustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('custom_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.customscript')),
                ('data_display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.datadisplay')),
            ],
            options={
                'db_table': 'DataDisplay_CustomScript',
                'ordering': ['order'],
                'unique_together': {('data_display', 'order')},
            },
        ),
        migrations.AddField(
            model_name='datadisplay',
            name='scripts',
            field=models.ManyToManyField(related_name='data_displays', through='eeg_api.DataDisplayCustomScript', to='eeg_api.customscript'),
        ),
        migrations.CreateModel(
            name='DataProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.dataprocesscategory')),
            ],
        ),
        migrations.CreateModel(
            name='DataProcessCustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('custom_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.customscript')),
                ('data_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.dataprocess')),
            ],
            options={
                'db_table': 'DataProcess_CustomScript',
                'ordering': ['order'],
                'unique_together': {('data_process', 'order')},
            },
        ),
        migrations.AddField(
            model_name='dataprocess',
            name='scripts',
            field=models.ManyToManyField(related_name='data_processes', through='eeg_api.DataProcessCustomScript', to='eeg_api.customscript'),
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Internal name or asset tag for this specific physical device (e.g., 'Lab Headset A')", max_length=150)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.devicemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceModelEEGChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.devicemodel')),
                ('eeg_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.eegchannel')),
            ],
            options={
                'db_table': 'DeviceModel_EEGChannel',
                'unique_together': {('device_model', 'eeg_channel')},
            },
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='channels',
            field=models.ManyToManyField(related_name='device_models', through='eeg_api.DeviceModelEEGChannel', to='eeg_api.eegchannel'),
        ),
        migrations.CreateModel(
            name='DeviceInstanceEEGChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_column_index', models.PositiveIntegerField(help_text='The exact column index (e.g., 0, 1, 2) in the EEG data file')),
                ('device_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.deviceinstance')),
                ('eeg_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.eegchannel')),
            ],
            options={
                'db_table': 'DeviceInstance_EEGChannel',
                'ordering': ['data_column_index'],
                'unique_together': {('device_instance', 'eeg_channel')},
            },
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='active_channels',
            field=models.ManyToManyField(related_name='device_instances', through='eeg_api.DeviceInstanceEEGChannel', to='eeg_api.eegchannel'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.medicalhistorycategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaDataDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_data_type', models.CharField(choices=[('STRING', 'String / Text'), ('INTEGER', 'Integer Number'), ('FLOAT', 'Floating Point Number'), ('BOOLEAN', 'True / False'), ('JSON', 'JSON Object')], default='STRING', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatacategory')),
            ],
        ),
        migrations.CreateModel(
            name='MetaDataGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatagroupcategory')),
            ],
        ),
        migrations.CreateModel(
            name='MetaDataGroupDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.metadatadefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.metadatagroup')),
            ],
            options={
                'db_table': 'MetaDataGroup_MetaDataDefinition',
                'ordering': ['order'],
                'unique_together': {('group', 'order')},
            },
        ),
        migrations.AddField(
            model_name='metadatagroup',
            name='definitions',
            field=models.ManyToManyField(related_name='groups', through='eeg_api.MetaDataGroupDefinition', to='eeg_api.metadatadefinition'),
        ),
        migrations.CreateModel(
            name='MetaDataGroupInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatagroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetaDataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatadefinition')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='eeg_api.metadatagroupinstance')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.event')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.page')),
            ],
            options={
                'db_table': 'Event_Page',
                'ordering': ['order'],
                'unique_together': {('event', 'order')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='pages',
            field=models.ManyToManyField(related_name='events', through='eeg_api.EventPage', to='eeg_api.page'),
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.component')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.page')),
            ],
            options={
                'db_table': 'Page_Component',
                'ordering': ['order'],
                'unique_together': {('page', 'order')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='components',
            field=models.ManyToManyField(related_name='pages', through='eeg_api.PageComponent', to='eeg_api.component'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField(help_text='The exact date and time the session started')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='eeg_api.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeartRateDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(help_text='File path or URI to the heart rate data', max_length=500)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_files', to='eeg_api.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EEGDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(help_text='File path or URI to the raw EDF/CSV data', max_length=500)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.deviceinstance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eeg_files', to='eeg_api.session')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source', models.CharField(help_text='Path or URI to the stimulus file/resource', max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.stimuluscategory')),
            ],
        ),
        migrations.CreateModel(
            name='StimulusPlaylistStimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of the stimulus in the playlist')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.stimulusplaylist')),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.stimulus')),
            ],
            options={
                'db_table': 'StimulusPlaylist_Stimulus',
                'ordering': ['order'],
                'unique_together': {('playlist', 'order')},
            },
        ),
        migrations.AddField(
            model_name='stimulusplaylist',
            name='stimuli',
            field=models.ManyToManyField(related_name='playlists', through='eeg_api.StimulusPlaylistStimulus', to='eeg_api.stimulus'),
        ),
        migrations.CreateModel(
            name='SubjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.medicalhistory')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.subjectprofile')),
            ],
            options={
                'db_table': 'SubjectProfile_MedicalHistory',
                'unique_together': {('subject', 'medical_history')},
            },
        ),
        migrations.AddField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='eeg_api.subjectprofile'),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='subjects',
            field=models.ManyToManyField(related_name='medical_histories', through='eeg_api.SubjectMedicalHistory', to='eeg_api.subjectprofile'),
        ),
        migrations.CreateModel(
            name='TriggerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EEGDataFileTriggerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eeg_data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.eegdatafile')),
                ('trigger_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.triggergroup')),
            ],
            options={
                'db_table': 'EEGDataFile_TriggerGroup',
                'unique_together': {('eeg_data_file', 'trigger_group')},
            },
        ),
        migrations.AddField(
            model_name='eegdatafile',
            name='trigger_groups',
            field=models.ManyToManyField(related_name='eeg_files', through='eeg_api.EEGDataFileTriggerGroup', to='eeg_api.triggergroup'),
        ),
        migrations.CreateModel(
            name='TriggerGroupDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.triggerdefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.triggergroup')),
            ],
            options={
                'unique_together': {('group', 'definition')},
            },
        ),
        migrations.AddField(
            model_name='triggergroup',
            name='triggers',
            field=models.ManyToManyField(related_name='trigger_groups', through='eeg_api.TriggerGroupDefinition', to='eeg_api.triggerdefinition'),
        ),
        migrations.CreateModel(
            name='TriggerPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('end_trigger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_ends', to='eeg_api.triggerdefinition')),
                ('start_trigger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_starts', to='eeg_api.triggerdefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EntityMetaDataRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('target_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('allowed_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.metadatagroupcategory')),
            ],
            options={
                'unique_together': {('target_table', 'allowed_category')},
            },
        ),
    ]
