# Generated by Django 6.0.3 on 2026-03-29 07:33

import django.db.models.deletion
import eeg_api.models.media
import eeg_api.models.recordings
import eeg_api.models.stimulus
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ComponentCategory',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Text Input Field'", max_length=100, unique=True)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ComponentType',
            },
        ),
        migrations.CreateModel(
            name='CustomScriptCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CustomScriptCategory',
            },
        ),
        migrations.CreateModel(
            name='CustomScriptLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'CustomScriptLanguage',
            },
        ),
        migrations.CreateModel(
            name='DataDisplayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DataDisplayCategory',
            },
        ),
        migrations.CreateModel(
            name='DataProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DataProcessCategory',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_eeg', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'DeviceModel',
            },
        ),
        migrations.CreateModel(
            name='DeviceModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DeviceModelCategory',
            },
        ),
        migrations.CreateModel(
            name='EEGChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Standardized channel name (e.g., 'Fp1', 'Cz')", max_length=50, unique=True)),
            ],
            options={
                'db_table': 'EEGChannel',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'EventCategory',
            },
        ),
        migrations.CreateModel(
            name='FrequencyBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('low_hz', models.FloatField()),
                ('high_hz', models.FloatField()),
            ],
            options={
                'db_table': 'FrequencyBand',
            },
        ),
        migrations.CreateModel(
            name='GenericRecordingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GenericRecordingCategory',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='LocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LocationCategory',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Manufacturer',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ManufacturerCategory',
            },
        ),
        migrations.CreateModel(
            name='MediaAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MediaAssetCategory',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MedicalHistoryCategoy',
            },
        ),
        migrations.CreateModel(
            name='MetaDataCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MetaDataCategory',
            },
        ),
        migrations.CreateModel(
            name='MetaDataGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'MetaDataGroupCategory',
            },
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PageCategory',
            },
        ),
        migrations.CreateModel(
            name='PageGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PageGroupCategory',
            },
        ),
        migrations.CreateModel(
            name='PlaylistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PlaylistCategory',
            },
        ),
        migrations.CreateModel(
            name='StimulusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'StimulusCategory',
            },
        ),
        migrations.CreateModel(
            name='TriggerDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_character', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'TriggerDefinition',
            },
        ),
        migrations.CreateModel(
            name='TriggerGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TriggerGroupCategory',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('parameter', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.componentcategory')),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.componenttype')),
            ],
            options={
                'db_table': 'Component',
            },
        ),
        migrations.CreateModel(
            name='CustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('source', models.TextField(help_text='File path or raw script code')),
                ('parameter', models.JSONField(blank=True, default=dict, help_text='Default JSON parameters for the script')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.customscriptcategory')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.customscriptlanguage')),
            ],
            options={
                'db_table': 'CustomScript',
            },
        ),
        migrations.CreateModel(
            name='DataDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.datadisplaycategory')),
            ],
            options={
                'db_table': 'DataDisplay',
            },
        ),
        migrations.CreateModel(
            name='DataDisplayCustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('custom_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.customscript')),
                ('data_display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.datadisplay')),
            ],
            options={
                'db_table': 'DataDisplay_CustomScript',
                'ordering': ['order'],
                'unique_together': {('data_display', 'order')},
            },
        ),
        migrations.AddField(
            model_name='datadisplay',
            name='scripts',
            field=models.ManyToManyField(related_name='data_displays', through='eeg_api.DataDisplayCustomScript', to='eeg_api.customscript'),
        ),
        migrations.CreateModel(
            name='DataProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.dataprocesscategory')),
            ],
            options={
                'db_table': 'DataProcess',
            },
        ),
        migrations.CreateModel(
            name='DataProcessCustomScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('custom_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.customscript')),
                ('data_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.dataprocess')),
            ],
            options={
                'db_table': 'DataProcess_CustomScript',
                'ordering': ['order'],
                'unique_together': {('data_process', 'order')},
            },
        ),
        migrations.AddField(
            model_name='dataprocess',
            name='scripts',
            field=models.ManyToManyField(related_name='data_processes', through='eeg_api.DataProcessCustomScript', to='eeg_api.customscript'),
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Internal name or asset tag for this specific physical device (e.g., 'Lab Headset A')", max_length=150)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.devicemodel')),
            ],
            options={
                'db_table': 'DeviceInstance',
            },
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_models', to='eeg_api.devicemodelcategory'),
        ),
        migrations.CreateModel(
            name='DeviceModelEEGChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.devicemodel')),
                ('eeg_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.eegchannel')),
            ],
            options={
                'db_table': 'DeviceModel_EEGChannel',
                'unique_together': {('device_model', 'eeg_channel')},
            },
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='channels',
            field=models.ManyToManyField(related_name='device_models', through='eeg_api.DeviceModelEEGChannel', to='eeg_api.eegchannel'),
        ),
        migrations.CreateModel(
            name='DeviceInstanceEEGChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_column_index', models.PositiveIntegerField(help_text='The exact column index (e.g., 0, 1, 2) in the EEG data file')),
                ('device_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.deviceinstance')),
                ('eeg_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.eegchannel')),
            ],
            options={
                'db_table': 'DeviceInstance_EEGChannel',
                'ordering': ['data_column_index'],
                'unique_together': {('device_instance', 'eeg_channel')},
            },
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='active_channels',
            field=models.ManyToManyField(related_name='device_instances', through='eeg_api.DeviceInstanceEEGChannel', to='eeg_api.eegchannel'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.eventcategory')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='eeg_api.location')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='eeg_api.event')),
            ],
            options={
                'db_table': 'EventGroup',
            },
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='eeg_api.event')),
            ],
            options={
                'db_table': 'EventRole',
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.locationcategory'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_models', to='eeg_api.manufacturer'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers', to='eeg_api.manufacturercategory'),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=eeg_api.models.media.media_directory_path)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('ICON', 'Icon'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='IMAGE', max_length=15)),
                ('original_filename', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='eeg_api.mediaassetcategory')),
            ],
            options={
                'db_table': 'MediaAsset',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logos', to='eeg_api.mediaasset'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_posters', to='eeg_api.mediaasset'),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.medicalhistorycategory')),
            ],
            options={
                'db_table': 'MedicalHistory',
            },
        ),
        migrations.CreateModel(
            name='MetaDataDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('expected_data_type', models.CharField(choices=[('STRING', 'String / Text'), ('INTEGER', 'Integer Number'), ('FLOAT', 'Floating Point Number'), ('BOOLEAN', 'True / False'), ('JSON', 'JSON Object')], default='STRING', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatacategory')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'MetaDataDefinition',
            },
        ),
        migrations.CreateModel(
            name='MetaDataGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatagroupcategory')),
            ],
            options={
                'db_table': 'MetaDataGroup',
            },
        ),
        migrations.CreateModel(
            name='MetaDataGroupDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.metadatadefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.metadatagroup')),
            ],
            options={
                'db_table': 'MetaDataGroup_MetaDataDefinition',
                'ordering': ['order'],
                'unique_together': {('group', 'order')},
            },
        ),
        migrations.AddField(
            model_name='metadatagroup',
            name='definitions',
            field=models.ManyToManyField(related_name='groups', through='eeg_api.MetaDataGroupDefinition', to='eeg_api.metadatadefinition'),
        ),
        migrations.CreateModel(
            name='MetaDataGroupInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatagroup')),
            ],
            options={
                'db_table': 'MetaDataGroupInstance',
            },
        ),
        migrations.CreateModel(
            name='MetaDataValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatadefinition')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='eeg_api.metadatagroupinstance')),
            ],
            options={
                'db_table': 'MetaDataValue',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.pagecategory')),
            ],
            options={
                'db_table': 'Page',
            },
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.component')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.page')),
            ],
            options={
                'db_table': 'Page_Component',
                'ordering': ['order'],
                'unique_together': {('page', 'order')},
            },
        ),
        migrations.AddField(
            model_name='page',
            name='components',
            field=models.ManyToManyField(related_name='pages', through='eeg_api.PageComponent', to='eeg_api.component'),
        ),
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.pagegroupcategory')),
            ],
            options={
                'db_table': 'PageGroup',
            },
        ),
        migrations.CreateModel(
            name='EventPageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.event')),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.pagegroup')),
            ],
            options={
                'db_table': 'Event_PageGroup',
                'unique_together': {('event', 'page_group')},
            },
        ),
        migrations.CreateModel(
            name='EventGroupPageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.eventgroup')),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.pagegroup')),
            ],
            options={
                'db_table': 'EventGroup_PageGroup',
                'unique_together': {('event_group', 'page_group')},
            },
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='page_groups',
            field=models.ManyToManyField(blank=True, related_name='event_groups', through='eeg_api.EventGroupPageGroup', to='eeg_api.pagegroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='page_groups',
            field=models.ManyToManyField(related_name='events', through='eeg_api.EventPageGroup', to='eeg_api.pagegroup'),
        ),
        migrations.CreateModel(
            name='PageGroupPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.page')),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.pagegroup')),
            ],
            options={
                'db_table': 'PageGroup_Page',
                'ordering': ['order'],
                'unique_together': {('page_group', 'order')},
            },
        ),
        migrations.AddField(
            model_name='pagegroup',
            name='pages',
            field=models.ManyToManyField(related_name='page_groups', through='eeg_api.PageGroupPage', to='eeg_api.page'),
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='AUDIO', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to=eeg_api.models.stimulus.stimulus_directory_path)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.stimuluscategory')),
            ],
            options={
                'db_table': 'Stimulus',
            },
        ),
        migrations.CreateModel(
            name='StimulusPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.playlistcategory')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StimulusPlaylist',
            },
        ),
        migrations.CreateModel(
            name='StimulusPlaylistStimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of the stimulus in the playlist')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.stimulusplaylist')),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.stimulus')),
            ],
            options={
                'db_table': 'StimulusPlaylist_Stimulus',
                'ordering': ['order'],
                'unique_together': {('playlist', 'order')},
            },
        ),
        migrations.AddField(
            model_name='stimulusplaylist',
            name='stimuli',
            field=models.ManyToManyField(related_name='playlists', through='eeg_api.StimulusPlaylistStimulus', to='eeg_api.stimulus'),
        ),
        migrations.CreateModel(
            name='SubjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SubjectProfile',
            },
        ),
        migrations.CreateModel(
            name='SubjectMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.medicalhistory')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.subjectprofile')),
            ],
            options={
                'db_table': 'SubjectProfile_MedicalHistory',
                'unique_together': {('subject', 'medical_history')},
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('start_datetime', models.DateTimeField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='eeg_api.event')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='eeg_api.location')),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='eeg_api.pagegroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='eeg_api.subjectprofile')),
            ],
            options={
                'db_table': 'Session',
                'unique_together': {('subject', 'event', 'page_group')},
            },
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='subjects',
            field=models.ManyToManyField(related_name='medical_histories', through='eeg_api.SubjectMedicalHistory', to='eeg_api.subjectprofile'),
        ),
        migrations.CreateModel(
            name='TriggerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.triggergroupcategory')),
            ],
            options={
                'db_table': 'TriggerGroup',
            },
        ),
        migrations.CreateModel(
            name='HeartRateDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=eeg_api.models.recordings.hr_directory_path)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.devicemodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_recordings', to='eeg_api.session')),
                ('trigger_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.triggergroup')),
            ],
            options={
                'db_table': 'HeartRateDataFile',
            },
        ),
        migrations.CreateModel(
            name='GenericRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=eeg_api.models.recordings.generic_directory_path)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.genericrecordingcategory')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_recordings', to='eeg_api.session')),
                ('trigger_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_recordings', to='eeg_api.triggergroup')),
            ],
            options={
                'db_table': 'GenericRecording',
            },
        ),
        migrations.CreateModel(
            name='EEGDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=eeg_api.models.recordings.eeg_directory_path)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.deviceinstance')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eeg_recordings', to='eeg_api.session')),
                ('trigger_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.triggergroup')),
            ],
            options={
                'db_table': 'EEGDataFile',
            },
        ),
        migrations.CreateModel(
            name='TriggerGroupDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.triggerdefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.triggergroup')),
            ],
            options={
                'db_table': 'TriggerGroup_TriggerDefinition',
                'unique_together': {('group', 'definition')},
            },
        ),
        migrations.AddField(
            model_name='triggergroup',
            name='triggers',
            field=models.ManyToManyField(related_name='trigger_groups', through='eeg_api.TriggerGroupDefinition', to='eeg_api.triggerdefinition'),
        ),
        migrations.CreateModel(
            name='TriggerPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('end_trigger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_ends', to='eeg_api.triggerdefinition')),
                ('start_trigger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pair_starts', to='eeg_api.triggerdefinition')),
            ],
            options={
                'db_table': 'TriggerPair',
            },
        ),
        migrations.CreateModel(
            name='ComponentDataDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.component')),
                ('data_display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.datadisplay')),
            ],
            options={
                'db_table': 'DataDisplay_Component',
                'ordering': ['order'],
                'unique_together': {('component', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ComponentDataProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.component')),
                ('data_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.dataprocess')),
            ],
            options={
                'db_table': 'DataProcess_Component',
                'ordering': ['order'],
                'unique_together': {('component', 'order')},
            },
        ),
        migrations.CreateModel(
            name='EventStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='eeg_api.eventgroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='eeg_api.eventrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EventStaffAssignment',
                'unique_together': {('user', 'role', 'event_group')},
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='eeg_api.event')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.mediaasset')),
            ],
            options={
                'db_table': 'Event_MediaAsset',
                'ordering': ['display_order'],
                'unique_together': {('event', 'media')},
            },
        ),
        migrations.CreateModel(
            name='EntityMetaDataRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('target_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('allowed_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.metadatagroupcategory')),
            ],
            options={
                'db_table': 'EntityMetaDataRegistry',
                'unique_together': {('target_table', 'allowed_category')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventgroup',
            unique_together={('event', 'name')},
        ),
        migrations.CreateModel(
            name='EventSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='eeg_api.event')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='eeg_api.eventgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='eeg_api.subjectprofile')),
            ],
            options={
                'db_table': 'EventSubjectAssignment',
                'unique_together': {('event', 'subject', 'group')},
            },
        ),
        migrations.CreateModel(
            name='TriggerHotkeyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('key_code', models.CharField(max_length=50)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.triggerdefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotkey_mappings', to='eeg_api.triggergroup')),
            ],
            options={
                'db_table': 'TriggerHotkeyMapping',
                'unique_together': {('group', 'key_code')},
            },
        ),
    ]
