# Generated by Django 6.0.3 on 2026-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0002_metadatagroup_changed_at_metadatagroup_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='scope',
            field=models.CharField(choices=[('ALL', 'All (Subject & Admin)'), ('SUBJECT', 'Subject Only'), ('ADMIN', 'Admin Only')], default='ALL', max_length=20),
        ),
    ]
