# Generated by Django 6.0.3 on 2026-03-15 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0002_alter_component_table_alter_componentcategory_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DeviceModelCategory',
            },
        ),
        migrations.AlterModelTable(
            name='medicalhistory',
            table='MedicalHistory',
        ),
        migrations.AlterModelTable(
            name='medicalhistorycategory',
            table='MedicalHistoryCategoy',
        ),
        migrations.AlterModelTable(
            name='subjectprofile',
            table='SubjectProfile',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_models', to='eeg_api.devicemodelcategory'),
        ),
    ]
