# Generated by Django 6.0.3 on 2026-04-04 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0003_page_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eegdatafile',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='genericrecording',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='heartratedatafile',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='eegdatafile',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Notizen des Admins', null=True),
        ),
        migrations.AddField(
            model_name='eegdatafile',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Reihenfolge bei mehreren Dateien'),
        ),
        migrations.AddField(
            model_name='genericrecording',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Notizen des Admins', null=True),
        ),
        migrations.AddField(
            model_name='genericrecording',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Reihenfolge bei mehreren Dateien'),
        ),
        migrations.AddField(
            model_name='heartratedatafile',
            name='description',
            field=models.TextField(blank=True, help_text='Optionale Notizen des Admins', null=True),
        ),
        migrations.AddField(
            model_name='heartratedatafile',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Reihenfolge bei mehreren Dateien'),
        ),
        migrations.AlterField(
            model_name='eegdatafile',
            name='device_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.deviceinstance'),
        ),
        migrations.AlterField(
            model_name='heartratedatafile',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.devicemodel'),
        ),
    ]
