# Generated by Django 6.0.3 on 2026-03-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0003_devicemodelcategory_alter_medicalhistory_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicemodel',
            name='max_channel_count',
        ),
    ]
