# Generated by Django 6.0.3 on 2026-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0004_alter_eegdatafile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eegdatafile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eegdatafile',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='genericrecording',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genericrecording',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='heartratedatafile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heartratedatafile',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
