# Generated by Django 6.0.3 on 2026-03-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0004_remove_devicemodel_max_channel_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subjectprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
