# Generated by Django 6.0.3 on 2026-04-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0005_alter_eegdatafile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='IMAGE', max_length=15),
        ),
    ]
