# Generated by Django 6.0.3 on 2026-04-09 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0006_alter_mediaasset_media_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectProfileInfoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SubjectProfileInfoCategory',
            },
        ),
        migrations.AddField(
            model_name='stimulus',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.playlistcategory')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Playlist',
            },
        ),
        migrations.CreateModel(
            name='PlaylistStimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of the stimulus in the playlist')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.playlist')),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.stimulus')),
            ],
            options={
                'db_table': 'Playlist_Stimulus',
                'ordering': ['order'],
                'unique_together': {('playlist', 'order')},
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='stimuli',
            field=models.ManyToManyField(related_name='playlists', through='eeg_api.PlaylistStimulus', to='eeg_api.stimulus'),
        ),
        migrations.CreateModel(
            name='SubjectProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Allgemeine Info', max_length=200)),
                ('description', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_infos', to='eeg_api.subjectprofile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.subjectprofileinfocategory')),
            ],
            options={
                'db_table': 'SubjectProfileInfo',
            },
        ),
        migrations.DeleteModel(
            name='ComponentDataDisplay',
        ),
        migrations.DeleteModel(
            name='ComponentDataProcess',
        ),
        migrations.DeleteModel(
            name='CustomScriptCategory',
        ),
        migrations.DeleteModel(
            name='CustomScriptLanguage',
        ),
        migrations.DeleteModel(
            name='CustomScript',
        ),
        migrations.DeleteModel(
            name='DataDisplayCategory',
        ),
        migrations.DeleteModel(
            name='DataDisplay',
        ),
        migrations.DeleteModel(
            name='DataDisplayCustomScript',
        ),
        migrations.DeleteModel(
            name='DataProcessCategory',
        ),
        migrations.DeleteModel(
            name='DataProcess',
        ),
        migrations.DeleteModel(
            name='DataProcessCustomScript',
        ),
        migrations.DeleteModel(
            name='MedicalHistoryCategory',
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
        migrations.DeleteModel(
            name='StimulusPlaylist',
        ),
        migrations.DeleteModel(
            name='StimulusPlaylistStimulus',
        ),
        migrations.DeleteModel(
            name='SubjectMedicalHistory',
        ),
    ]
