# Generated by Django 6.0.3 on 2026-03-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0006_triggerhotkeymapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='stimulus',
            name='duration',
            field=models.PositiveIntegerField(default=10, help_text='Duration in seconds'),
        ),
    ]
