# Generated by Django 6.0.3 on 2026-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0007_subjectprofileinfocategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stimulus',
            name='type',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CUSTOM', 'Custom')], default='AUDIO', max_length=10),
        ),
    ]
