# Generated by Django 6.0.3 on 2026-04-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0008_alter_stimulus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadatagroupinstance',
            name='creation_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Registry Assignment'), ('COMPONENT', 'Automated Component / Session')], default='MANUAL', max_length=20),
        ),
    ]
