# Generated by Django 6.0.3 on 2026-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0008_manufacturer_alter_devicemodel_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
