# Generated by Django 6.0.3 on 2026-04-29 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0009_metadatagroupinstance_creation_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinstance',
            name='active_channels',
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='model',
        ),
        migrations.RemoveField(
            model_name='deviceinstance',
            name='name',
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='device_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='eeg_api.devicemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='final_channels',
            field=models.JSONField(blank=True, default=dict, help_text='JSON dict of channels and their status, e.g., {"Fp1": "GOOD", "Fz": "NOISY"}'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='metadata_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_device_instance', to='eeg_api.metadatagroupinstance'),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_instances', to='eeg_api.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='default_settings',
            field=models.OneToOneField(blank=True, help_text='Factory default variables (Cloned downstream)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_for_device_model', to='eeg_api.metadatagroupinstance'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='hardware_specs',
            field=models.OneToOneField(blank=True, help_text='Immutable hardware facts (Never cloned downstream)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specs_for_device_model', to='eeg_api.metadatagroupinstance'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_pools', to='eeg_api.devicemodel')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_pool', to='eeg_api.event')),
            ],
            options={
                'db_table': 'Event_DeviceModel',
                'unique_together': {('event', 'device_model')},
            },
        ),
        migrations.CreateModel(
            name='EventGroupPageGroupDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_channels', models.JSONField(blank=True, default=list, help_text='List of expected channel names selected from Master, e.g., ["Fp1", "Fp2", "Cz"]')),
                ('device_from_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_configs', to='eeg_api.eventdevicemodel')),
                ('metadata_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_device_config', to='eeg_api.metadatagroupinstance')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_configs', to='eeg_api.eventgrouppagegroup')),
            ],
            options={
                'db_table': 'EventGroupPageGroup_Device',
                'unique_together': {('phase', 'device_from_pool')},
            },
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='phase_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='eeg_api.eventgrouppagegroupdevice'),
        ),
        migrations.DeleteModel(
            name='DeviceInstanceEEGChannel',
        ),
    ]
