# Generated by Django 6.0.3 on 2026-03-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0009_alter_devicemodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PageCategory',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.pagecategory'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ComponentDataDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.component')),
                ('data_display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.datadisplay')),
            ],
            options={
                'db_table': 'DataDisplay_Component',
                'ordering': ['order'],
                'unique_together': {('component', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ComponentDataProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.component')),
                ('data_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.dataprocess')),
            ],
            options={
                'db_table': 'DataProcess_Component',
                'ordering': ['order'],
                'unique_together': {('component', 'order')},
            },
        ),
    ]
