# Generated by Django 6.0.3 on 2026-04-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0010_remove_deviceinstance_active_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartratedatafile',
            name='device_model',
        ),
        migrations.AddField(
            model_name='genericrecording',
            name='device_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.deviceinstance'),
        ),
        migrations.AddField(
            model_name='heartratedatafile',
            name='device_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.deviceinstance'),
        ),
    ]
