# Generated by Django 6.0.3 on 2026-03-21 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0010_pagecategory_page_category_componentdatadisplay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'PageGroupCategory',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='pages',
        ),
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.pagegroupcategory')),
            ],
            options={
                'db_table': 'PageGroup',
            },
        ),
        migrations.CreateModel(
            name='EventPageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.event')),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.pagegroup')),
            ],
            options={
                'db_table': 'Event_PageGroup',
                'unique_together': {('event', 'page_group')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='page_groups',
            field=models.ManyToManyField(related_name='events', through='eeg_api.EventPageGroup', to='eeg_api.pagegroup'),
        ),
        migrations.CreateModel(
            name='PageGroupPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.page')),
                ('page_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.pagegroup')),
            ],
            options={
                'db_table': 'PageGroup_Page',
                'ordering': ['order'],
                'unique_together': {('page_group', 'order')},
            },
        ),
        migrations.AddField(
            model_name='pagegroup',
            name='pages',
            field=models.ManyToManyField(related_name='page_groups', through='eeg_api.PageGroupPage', to='eeg_api.page'),
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
    ]
