# Generated by Django 6.0.3 on 2026-04-29 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0011_remove_heartratedatafile_device_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinstance',
            old_name='metadata_instance',
            new_name='metadata_overwrite_instance',
        ),
        migrations.AddField(
            model_name='eventgrouppagegroupdevice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deviceinstance',
            name='phase_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='eeg_api.eventgrouppagegroupdevice'),
        ),
    ]
