# Generated by Django 6.0.3 on 2026-03-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0011_pagegroupcategory_remove_event_pages_pagegroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerpair',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='triggerpair',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='triggerpair',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='triggerpair',
            name='created_by',
        ),
    ]
