# Generated by Django 6.0.3 on 2026-03-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0012_remove_triggerpair_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Text Input Field'", max_length=100, unique=True)),
                ('identifier', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ComponentType',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.componenttype'),
            preserve_default=False,
        ),
    ]
