# Generated by Django 6.0.3 on 2026-04-29 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0012_rename_metadata_instance_deviceinstance_metadata_overwrite_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinstance',
            name='phase_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='eeg_api.eventgrouppagegroupdevice'),
            preserve_default=False,
        ),
    ]
