# Generated by Django 6.0.3 on 2026-05-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0013_alter_deviceinstance_phase_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatagroupinstance',
            name='creation_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Registry Assignment'), ('COMPONENT', 'Automated Component / Session'), ('DEVICE', 'Device Settings / Specs')], default='MANUAL', max_length=20),
        ),
    ]
