# Generated by Django 6.0.3 on 2026-03-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0014_eventcategory_event_event_end_event_event_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartratedatafile',
            name='device_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.devicemodel'),
            preserve_default=False,
        ),
    ]
