# Generated by Django 6.0.3 on 2026-05-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0014_alter_metadatagroupinstance_creation_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatagroupinstance',
            name='creation_source',
            field=models.CharField(choices=[('MANUAL', 'Manual Registry Assignment'), ('COMPONENT', 'Automated Component / Session'), ('DEVICE', 'Device Settings / Specs'), ('DEVICE_DEFAULT_SETTINGS', 'Device Default Settings'), ('DEVICE_PHASE', 'Device Phase Defaults'), ('DEVICE_INSTANCE', 'Device Instance Setup')], default='MANUAL', max_length=30),
        ),
    ]
