# Generated by Django 6.0.3 on 2026-03-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0015_heartratedatafile_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='page_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='eeg_api.pagegroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eegdatafile',
            name='source',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='frequencyband',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='heartratedatafile',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.devicemodel'),
        ),
        migrations.AlterField(
            model_name='heartratedatafile',
            name='source',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('subject', 'event', 'page_group')},
        ),
    ]
