# Generated by Django 6.0.3 on 2026-03-26 09:00

import django.db.models.deletion
import eeg_api.models.media
import eeg_api.models.recordings
import eeg_api.models.stimulus
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0018_stimulus_changed_at_stimulus_changed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericRecordingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eegdatafile',
            name='trigger_groups',
        ),
        migrations.RemoveField(
            model_name='eegdatafile',
            name='source',
        ),
        migrations.RemoveField(
            model_name='heartratedatafile',
            name='note',
        ),
        migrations.RemoveField(
            model_name='heartratedatafile',
            name='source',
        ),
        migrations.RemoveField(
            model_name='stimulus',
            name='source',
        ),
        migrations.AddField(
            model_name='eegdatafile',
            name='file',
            field=models.FileField(default=1, upload_to=eeg_api.models.recordings.eeg_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eegdatafile',
            name='trigger_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.triggergroup'),
        ),
        migrations.AddField(
            model_name='heartratedatafile',
            name='file',
            field=models.FileField(default=1, upload_to=eeg_api.models.recordings.hr_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heartratedatafile',
            name='trigger_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.triggergroup'),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=eeg_api.models.stimulus.stimulus_directory_path),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='type',
            field=models.CharField(choices=[('AUDIO', 'Audio'), ('IMAGE', 'Image'), ('VIDEO', 'Video')], default='AUDIO', max_length=10),
        ),
        migrations.AlterField(
            model_name='eegdatafile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eeg_recordings', to='eeg_api.session'),
        ),
        migrations.AlterField(
            model_name='heartratedatafile',
            name='device_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.devicemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heartratedatafile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_recordings', to='eeg_api.session'),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='eegdatafile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='heartratedatafile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='stimulus',
            table=None,
        ),
        migrations.CreateModel(
            name='GenericRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=eeg_api.models.recordings.generic_directory_path)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generic_recordings', to='eeg_api.session')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eeg_api.genericrecordingcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=eeg_api.models.media.media_directory_path)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('ICON', 'Icon'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='IMAGE', max_length=15)),
                ('original_filename', models.CharField(max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_changed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='eeg_api.mediaassetcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='eeg_api.event')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eeg_api.mediaasset')),
            ],
            options={
                'db_table': 'Event_MediaAsset',
                'ordering': ['display_order'],
                'unique_together': {('event', 'media')},
            },
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logos', to='eeg_api.mediaasset'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_posters', to='eeg_api.mediaasset'),
        ),
        migrations.DeleteModel(
            name='EEGDataFileTriggerGroup',
        ),
    ]
