# Generated by Django 6.0.3 on 2026-03-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0019_genericrecordingcategory_mediaassetcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcategory',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='poster',
        ),
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logos', to='eeg_api.mediaasset'),
        ),
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_posters', to='eeg_api.mediaasset'),
        ),
        migrations.AlterModelTable(
            name='eegdatafile',
            table='EEGDataFile',
        ),
        migrations.AlterModelTable(
            name='genericrecording',
            table='GenericRecording',
        ),
        migrations.AlterModelTable(
            name='genericrecordingcategory',
            table='GenericRecordingCategory',
        ),
        migrations.AlterModelTable(
            name='heartratedatafile',
            table='HeartRateDataFile',
        ),
        migrations.AlterModelTable(
            name='mediaasset',
            table='MediaAsset',
        ),
        migrations.AlterModelTable(
            name='mediaassetcategory',
            table='MediaAssetCategory',
        ),
        migrations.AlterModelTable(
            name='stimulus',
            table='Stimulus',
        ),
    ]
