# Generated by Django 6.0.3 on 2026-03-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0021_subjectprofile_user_eventgroup_eventrole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericrecording',
            name='trigger_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generic_recordings', to='eeg_api.triggergroup'),
        ),
    ]
