# Generated by Django 6.0.3 on 2026-03-27 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0023_locationcategory_playlistcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.componentcategory'),
        ),
        migrations.AlterField(
            model_name='customscript',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.customscriptcategory'),
        ),
        migrations.AlterField(
            model_name='datadisplay',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.datadisplaycategory'),
        ),
        migrations.AlterField(
            model_name='dataprocess',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.dataprocesscategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.eventcategory'),
        ),
        migrations.AlterField(
            model_name='genericrecording',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.genericrecordingcategory'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.medicalhistorycategory'),
        ),
        migrations.AlterField(
            model_name='metadatadefinition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatacategory'),
        ),
        migrations.AlterField(
            model_name='metadatagroup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.metadatagroupcategory'),
        ),
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.pagecategory'),
        ),
        migrations.AlterField(
            model_name='pagegroup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.pagegroupcategory'),
        ),
        migrations.AlterField(
            model_name='stimulus',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='eeg_api.stimuluscategory'),
        ),
    ]
