# Generated by Django 6.0.3 on 2026-03-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0024_alter_component_category_alter_customscript_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ManufacturerCategory',
            },
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturers', to='eeg_api.manufacturercategory'),
        ),
    ]
