# Generated by Django 6.0.3 on 2026-03-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg_api', '0025_manufacturercategory_manufacturer_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventsubjectassignment',
            unique_together={('event', 'subject', 'group')},
        ),
    ]
